### ISSUE TITLE
Schemas with anyOf have dicts when accessed for the first time

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#2668]
For schema entries that use `anyOf`, our datamodels code mangles it into a *dict* when accessed for the first time.  So an snippet from the core schema showing the section for `meta.instrument.channel`:
```yaml
      instrument:
        title: Instrument configuration information
        type: object
        properties:
          name:
            title: Instrument used to acquire the data
            type: string
            enum: [NIRCAM, NIRSPEC, MIRI, TFI, FGS, NIRISS, ANY, N/A]
            fits_keyword: INSTRUME
            blend_table: True
          detector:
            title: Name of detector used to acquire the data
            type: string
            enum: [NRCA1, NRCA2, NRCA3, NRCA4, NRCALONG, NRCB1, NRCB2, NRCB3, NRCB4,
              NRCBLONG, NRS1, NRS2, ANY, MIRIMAGE, MIRIFULONG, MIRIFUSHORT,
              NIS, GUIDER1, GUIDER2, N/A]
            fits_keyword: DETECTOR
            blend_table: True
          module:
            title: 'NIRCam module: A or B'
            type: string
            fits_keyword: MODULE
            blend_table: True
          channel:
            title: 'NIRCam channel: long or short'
            type: string
            # Values grouped by instrument:
            anyOf:
              # MIRI
              - enum:
                 ['1', '2', '3', '4', '12', '34', '123', '234', '1234']
              # NIRCam
              - enum:
                  [LONG, SHORT]
              # All
              - enum:
                  [ANY, N/A]
            fits_keyword: CHANNEL
            blend_table: True
```
Here's the test case:
```
In [1]: from jwst import datamodels

In [2]: im = datamodels.ImageModel((100, 100))

In [3]: im.meta.instance
Out[3]: {'date': '2018-10-05T13:30:29.437', 'model_type': 'ImageModel'}

In [4]: im.meta.instrument.channel
Out[4]: <jwst.datamodels.properties.ObjectNode at 0xb1ed4f160>

In [5]: # That is not correct.  It should return None

In [6]: # Let's find out what is inside the node

In [7]: im.meta.instrument.channel.instance
Out[7]: {}
```
We are seeing that when a property in the `meta` tree is accessed via a datamodel, and that property has an `anyOf`, then we see this behavior. i.e. when you go to set the parameter back to `None` or just simply be write out the model above:
```
In [8]: im.save('test.fits')
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-8-90e45fda3c01> in <module>()
----> 1 im.save('test.fits')

~/dev/jwst/jwst/datamodels/model_base.py in save(self, path, dir_path, *args, **kwargs)
    499             if 'clobber' not in kwargs:
    500                 kwargs.setdefault('overwrite', True)
--> 501             self.to_fits(output_path, *args, **kwargs)
    502         elif ext == '.asdf':
    503             self.to_asdf(output_path, *args, **kwargs)

~/dev/jwst/jwst/datamodels/model_base.py in to_fits(self, init, *args, **kwargs)
    582 
    583         with fits_support.to_fits(self._instance, self._schema,
--> 584                                   extensions=self._extensions) as ff:
    585             with warnings.catch_warnings():
    586                 warnings.filterwarnings('ignore', message='Card is too long')

~/dev/jwst/jwst/datamodels/fits_support.py in to_fits(tree, schema, extensions)
    384     hdulist.append(fits.PrimaryHDU())
    385 
--> 386     _save_from_schema(hdulist, tree, schema)
    387     _save_extra_fits(hdulist, tree)
    388     _save_history(hdulist, tree)

~/dev/jwst/jwst/datamodels/fits_support.py in _save_from_schema(hdulist, tree, schema)
    338     validator.comment_stack = []
    339     # This actually kicks off the saving
--> 340     validator.validate(tree, _schema=schema)
    341 
    342 

~/anaconda3/envs/jwst_dev/lib/python3.7/site-packages/jsonschema/validators.py in validate(self, *args, **kwargs)
    128         def validate(self, *args, **kwargs):
    129             for error in self.iter_errors(*args, **kwargs):
--> 130                 raise error
    131 
    132         def is_type(self, instance, type):

ValidationError: {} is not of type 'string'

Failed validating 'type' in schema['properties']['meta']['properties']['instrument']['properties']['channel']:
    OrderedDict([('title', 'NIRCam channel: long or short'),
                 ('type', 'string'),
                 ('anyOf',
                  [OrderedDict([('enum',
                                 ['1',
                                  '2',
                                  '3',
                                  '4',
                                  '12',
                                  '34',
                                  '123',
                                  '234',
                                  '1234'])]),
                   OrderedDict([('enum', ['LONG', 'SHORT'])]),
                   OrderedDict([('enum', ['ANY', 'N/A'])])]),
                 ('fits_keyword', 'CHANNEL'),
                 ('blend_table', True),
                 ('$schema',
                  'http://stsci.edu/schemas/asdf-schema/0.1.0/asdf-schema')])

On instance['meta']['instrument']['channel']:
    {}
```
This is causing problems in the pipeline regression tests right now because `modelblender` accesses lots of header keywords of a datamodel, and then that datamodel needs to be written out.  But any of the keywords that have `anyOf` and have been accessed now have the above behavior.
