### ISSUE TITLE
Reorganize reference file documentation in JWST pipeline

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#2675]
There are several different links for documentation in different places.  Here are some things that should be improved:

- [x] Linking together the high level pages
- [x] Removing the old ref_file_doc_DMS_65
- [x] look at ways to handle the linkage between steps and reference files
- [x] Assure that all reference file pages have the same format using including the standard keywords, format for the files, and include selection criteria

**Comment by sosey** [comment]
related: #2536

**Comment by jaytmiller** [comment]
CRDS probably has this in it's repro pseudo reference,  which may be a start:

```
steps_to_reftypes:
  assign_wcs: [camera, collimator, disperser, distortion, filteroffset, fore, fpa,
    ifufore, ifupost, ifuslicer, msa, ote, regions, specwcs, wavelengthrange]
  barshadow: [barshadow]
  bkg_subtract: [wavelengthrange, wfssbkg]
  cube_build: [cubepar, resol]
  dark_current: [dark]
  dq_init: [mask]
  extract_1d: [extract1d]
  extract_2d: [wavecorr, wavelengthrange]
  firstframe: []
  flat_field: [dflat, fflat, flat, sflat]
  fringe: [fringe]
  gain_scale: [gain]
  group_scale: []
  guider_cds: []
  imprint_subtract: []
  ipc: [ipc]
  jump: [gain, readnoise]
  lastframe: []
  linearity: [linearity]
  msa_flagging: [msaoper]
  pathloss: [pathloss]
  persistence: [persat, trapdensity, trappars]
  photom: [area, photom]
  ramp_fit: [gain, readnoise]
  refpix: [refpix]
  resample: [drizpars]
  resample_spec: [drizpars]
  rscd: [rscd]
  saturation: [saturation]
  srctype: []
  straylight: [straymask]
  superbias: [superbias]

```
