### ISSUE TITLE
Datamodels schemas should be ASDF compliant

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#3291]
Our current schemas in `datamodels` are not ASDF-compliant.  They should be.  That means a change something like going from this:
```
allOf:
- $ref: referencefile.schema.yaml
- $ref: keyword_exptype.schema.yaml
- $ref: keyword_filter.schema.yaml
- $ref: keyword_pixelarea.schema.yaml
- $ref: keyword_pupil.schema.yaml

- type: object
  properties:
    data:
      title: The pixel area array
      fits_hdu: SCI
      default: 1.0
      ndim: 2
      datatype: float32
$schema: http://stsci.edu/schemas/fits-schema/fits-schema
```
to this
```
%YAML 1.1
---
$schema: "http://stsci.edu/schemas/fits-schema/fits-schema"
id: "http://stsci.edu/schemas/jwst_datamodel/pixelarea.schema"
description: |
  A schema describing the the pixel area reference file

allOf:
- $ref: http://stsci.edu/schemas/jwst_datamodel/referencefile.schema
- $ref: http://stsci.edu/schemas/jwst_datamodel/keyword_exptype.schema
- $ref: http://stsci.edu/schemas/jwst_datamodel/keyword_filter.schema
- $ref: http://stsci.edu/schemas/jwst_datamodel/keyword_pixelarea.schema
- $ref: http://stsci.edu/schemas/jwst_datamodel/keyword_pupil.schema

- type: object
  properties:
    data:
      title: The pixel area array
      fits_hdu: SCI
      default: 1.0
      ndim: 2
      datatype: float32
```
Though it is unclear if we need the full URL in the `$ref:` line for each referenced schema.

Would be happy to get feedback from @drdavella and @nden.
