### ISSUE TITLE
top-level in-memory schema has wrong id

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6140]
_Issue [JP-2137](https://jira.stsci.edu/browse/JP-2137) was created on JIRA by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies):_

The in-memory combined schema in a datamodel has the `id` attribute munged by whatever is the last included schema.

So as an example in `jwst` package, the gain schema is

```
%YAML 1.1
---
$schema: "http://stsci.edu/schemas/fits-schema/fits-schema"
id: "http://stsci.edu/schemas/jwst_datamodel/gain.schema"
allOf:
- $ref: referencefile.schema
- $ref: subarray.schema
- $ref: bunit.schema
- $ref: keyword_gainfact.schema
- type: object
  properties:
    data:
      title: The gain
      fits_hdu: SCI
      default: 0.0
      ndim: 2
      datatype: float32
```

And when a `GainModel` is created:

```
In [1]: from jwst import datamodels

In [2]: m = datamodels.GainModel()

In [3]: m._schema
Out[3]: 
OrderedDict([('$schema', 'http://stsci.edu/schemas/fits-schema/fits-schema'),
             ('id',
              'http://stsci.edu/schemas/jwst_datamodel/keyword_gainfact.schema'),
             ('type', 'object'),
             ('properties',
              OrderedDict([('meta',
                            OrderedDict([('type', 'object'),
                                         ('properties',
```

the `id` attribute is munged by the last included `$ref` id.  So this is probably a bug in

<https://github.com/spacetelescope/stdatamodels/blob/fc3c2c9c62d7700114ad48560721302412c65a84/src/stdatamodels/schema.py#L152>
