### ISSUE TITLE
Use tmp_path instead of tmpdir pytest fixture

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#8311]
Replace all instances `tmpdir` and `tmpdir_factory` pytest fixtures with `tmp_path` and `tmp_path_factory` fixtures, respectively.

Then in pyproject.toml:

```toml
[tool.pytest.ini_options]
addopts = [
    "-p no:legacypath",
]
```

which will prevent it from being used in the future.  This is will make the code more robust for use of `pathlib.Path` instances in the runtime code.
