### ISSUE TITLE
scripts in the project.scripts section are missing main function or completely absent

### ISSUE THREAD

**Issue by Hellseher** [spacetelescope/jwst#9401]
Hi

During refresh JWST to 1.18.0 package in Guix index I've faced with issue during
sanity check which tries to load the module and it's scripts.

https://github.com/spacetelescope/jwst/blob/1b78507c7eb7fb2ab81f014112e015503f449d98/pyproject.toml#L66C1-L86C48
``` toml
[project.scripts]
adjust_wcs = "jwst.scripts.adjust_wcs:main"
asn_edit = "jwst.scripts.asn_edit:main"
asn_from_list = "jwst.associations.asn_from_list:main"
asn_gather = "jwst.scripts.asn_gather:main"
asn_generate = "jwst.associations.main:main"
asn_make_pool = "jwst.scripts.asn_make_pool:main"
collect_pipeline_cfgs = "jwst.scripts.collect_pipeline_cfgs:main"
create_data = "jwst.scripts.create_data:main"
csvconvert = "jwst.csv_tools.csvconvert:CSVConvertScript"
exp_to_source = "jwst.exp_to_source.main:Main"
pointing_summary = "jwst.scripts.pointing_summary:main"
schemadoc = "jwst.scripts.schemadoc:main"
set_telescope_pointing = "jwst.scripts.set_telescope_pointing:main"
"set_telescope_pointing.py" = "jwst.scripts.set_telescope_pointing:deprecated_name"
set_velocity_aberration = "jwst.scripts.set_velocity_aberration:main"
"set_velocity_aberration.py" = "jwst.scripts.set_velocity_aberration:deprecated_name"
stfitsdiff = "jwst.scripts.stfitsdiff:main"
v1_calculate = "jwst.scripts.v1_calculate:main"
verify_install_requires = "jwst.scripts.verify_install_requires:main"
world_coords = "jwst.scripts.world_coords:main"
```
## AttributeError: module 'jwst.scripts.asn_gather' has no attribute 'main'

There is no `main` function in that script:

``` pyton
#!/usr/bin/env python

"""asn_gather: Copy or Move data that is listed in an association"""

from jwst.associations import asn_gather

if __name__ == '__main__':
    kwargs = asn_gather.from_cmdline()
    asn_gather.asn_gather(**kwargs)
```
## ModuleNotFoundError: No module named 'jwst.scripts.create_data'

There is no `create_data` script
```
drwxr-xr-x  3 4.0K Apr 21 10:11 .
drwxr-xr-x 69 4.0K Apr 21 10:11 ..
-rwxr-xr-x  1 8.1K Apr 21 10:11 adjust_wcs.py
-rw-r--r--  1 2.5K Apr 21 10:11 asn_edit.py
-rw-r--r--  1  237 Apr 21 10:11 asn_gather.py
-rw-r--r--  1  282 Apr 21 10:11 asn_make_pool.py
-rwxr-xr-x  1 1.4K Apr 21 10:11 collect_pipeline_cfgs.py
-rw-r--r--  1    0 Apr 21 10:11 __init__.py
-rwxr-xr-x  1 1.7K Apr 21 10:11 pointing_summary.py
-rwxr-xr-x  1 3.1K Apr 21 10:11 schemadoc.py
-rwxr-xr-x  1 7.0K Apr 21 10:11 set_telescope_pointing.py
-rwxr-xr-x  1 1.7K Apr 21 10:11 set_velocity_aberration.py
-rwxr-xr-x  1 6.0K Apr 21 10:11 stfitsdiff.py
drwxr-xr-x  2   55 Apr 21 10:11 tests
-rwxr-xr-x  1 4.4K Apr 21 10:11 v1_calculate.py
-rw-r--r--  1  918 Apr 21 10:11 verify_install_requires.py
-rwxr-xr-x  1  14K Apr 21 10:11 world_coords.py
```

## ModuleNotFoundError: No module named 'jwst.csv_tools'

It was removed according to changelog https://github.com/spacetelescope/jwst/blob/6ea5119310aa09592907b2c9d0957cd491b325a9/CHANGES.rst#L5040
